// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using N5User.Data.Context;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace N5User.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("N5User.Data.Models.Permission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasComment("Unique Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("EmployeeForename")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasComment("Employee Forename");

                    b.Property<string>("EmployeeSurname")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasComment("Employee Surename");

                    b.Property<DateTime>("PermissionDate")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Permission granted on date");

                    b.Property<int>("PermissionTypeId")
                        .HasColumnType("integer")
                        .HasComment("Permission Type");

                    b.HasKey("Id");

                    b.HasIndex("PermissionTypeId");

                    b.ToTable("Permissions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EmployeeForename = "Michael",
                            EmployeeSurname = "Scott",
                            PermissionDate = new DateTime(2024, 3, 31, 22, 47, 37, 610, DateTimeKind.Local).AddTicks(6480),
                            PermissionTypeId = 1
                        },
                        new
                        {
                            Id = 2,
                            EmployeeForename = "Pam",
                            EmployeeSurname = "Beasly",
                            PermissionDate = new DateTime(2024, 3, 31, 22, 47, 37, 610, DateTimeKind.Local).AddTicks(6520),
                            PermissionTypeId = 2
                        },
                        new
                        {
                            Id = 3,
                            EmployeeForename = "Jim",
                            EmployeeSurname = "Halpert",
                            PermissionDate = new DateTime(2024, 3, 31, 22, 47, 37, 610, DateTimeKind.Local).AddTicks(6520),
                            PermissionTypeId = 2
                        });
                });

            modelBuilder.Entity("N5User.Data.Models.PermissionType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasComment("Unique Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasComment("Permission description");

                    b.HasKey("Id");

                    b.ToTable("PermissionTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Manager"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Admin"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Sales"
                        });
                });

            modelBuilder.Entity("N5User.Data.Models.Permission", b =>
                {
                    b.HasOne("N5User.Data.Models.PermissionType", "PermissionType")
                        .WithMany("Permissions")
                        .HasForeignKey("PermissionTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PermissionType");
                });

            modelBuilder.Entity("N5User.Data.Models.PermissionType", b =>
                {
                    b.Navigation("Permissions");
                });
#pragma warning restore 612, 618
        }
    }
}
